### ISSUE TITLE
add train stations

### ISSUE THREAD

**Issue by jbalzer12** [phuef/Geoinformation-in-Society-22#117]

**Comment by jbalzer12** [comment]
@xcomagent95 will collect the data and bring it to a geojson file
@jbalzer12 will present the data in the map application (frontend)

**Comment by xcomagent95** [comment]
{
"type": "FeatureCollection",
"name": "train_stations",
"features": [
{ "type": "Feature", "properties": { "name": "Hauptbahnhof Münster" }, "geometry": { "type": "Point", "coordinates": [ 7.635792033837703, 51.956404011734264 ] } },
{ "type": "Feature", "properties": { "name": "Bahnhof Mecklenbeck" }, "geometry": { "type": "Point", "coordinates": [ 7.579460657379059, 51.923974673993456 ] } },
{ "type": "Feature", "properties": { "name": "Bahnhof Westbevern" }, "geometry": { "type": "Point", "coordinates": [ 7.743798843035933, 52.031066603557889 ] } },
{ "type": "Feature", "properties": { "name": "Bahnhof Roxel" }, "geometry": { "type": "Point", "coordinates": [ 7.52643558472252, 51.946254971264977 ] } }
]
}

**Comment by jbalzer12** [comment]
[Pull request](https://github.com/phuef/Geoinformation-in-Society-22/pull/122)

**Comment by xcomagent95** [comment]
Oha...Entschuldige bitte :0 Review ist raus
